version: "3.8"
services:
  node:
    container_name: github-actions-env-toolkit-builder
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    command: "tail -f /dev/null"
